import Portfolio from './Portfolio';

// About is the home page. The other five sections are routes generated by
// [section]/page.tsx; all six render the same client component.
export default function Home() {
  return <Portfolio section="about" />;
}
